"""add website table

Revision ID: a426faeeb362
Revises: 91979b40eb38
Create Date: 2022-02-27 00:00:14.749467-08:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a426faeeb362'
down_revision = '91979b40eb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website',
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('avg_bias', sa.Float(), nullable=False),
                    sa.Column('num_data_points', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('url')
                    )
    op.create_index(op.f('ix_website_url'), 'website', ['url'], unique=True)
    op.alter_column('user', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('user', 'is_superuser',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'is_superuser',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('user', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.drop_index(op.f('ix_website_url'), table_name='website')
    op.drop_table('website')
    # ### end Alembic commands ###
